#!/bin/bash

PORT=${PORT-5000}
api_url='http://localhost:'${PORT}
submit_url=${api_url}'/app/submit'

submit_app() {
    curl -X POST ${submit_url} -d "${1}"
    echo
}

# Satisfactory mobile sites.
submit_app 'name=A List Apart&app_url=http://alistapart.com/'
submit_app 'name=CSS-Tricks&app_url=http://css-tricks.com/'
submit_app 'name=Codepen&app_url=http://codepen.io/'
submit_app 'name=Currys&app_url=http://www.currys.co.uk/'
submit_app 'name=Disney&app_url=http://disney.com/'
submit_app 'name=Facebook&app_url=http://facebook.com/'
submit_app 'name=Forecast&app_url=http://forecast.io/&category=weather'
submit_app 'name=Fray&app_url=http://fray.com/'
submit_app 'name=GitHub&app_url=http://github.com/'
submit_app 'name=Heroku Status&app_url=https://status.heroku.com/'
submit_app 'name=Hipmunk&app_url=http://hipmunk.com/&category=travel'
submit_app 'name=Lotta Nieminen&app_url=http://www.lottanieminen.com/'
submit_app 'name=Marketplace&app_url=https://marketplace.firefox.com/'
submit_app 'name=Microsoft&app_url=http://www.microsoft.com/'
submit_app 'name=Open Table&app_url=http://opentable.com/'
submit_app 'name=Polygon&app_url=http://www.polygon.com/'
submit_app 'name=Starbucks&app_url=http://www.starbucks.com/'
submit_app 'name=Tattly&app_url=http://tattly.com/'
submit_app 'name=The Next Web&app_url=http://thenextweb.com/'
submit_app 'name=The Shape of Design&app_url=http://www.shapeofdesignbook.com/'
submit_app 'name=Time&app_url=http://time.com/'
submit_app 'name=Twitter&app_url=http://twitter.com/'
submit_app 'name=United Pixel Workers&app_url=http://www.unitedpixelworkers.com/'
submit_app 'name=Wikipedia&app_url=http://wikipedia.com/'

# Questionable mobile sites.
# submit_app 'name=American Express&app_url=http://www.amexmobile.com/&category=business'
# submit_app 'name=Bank of America&app_url=http://bofa.mobi/&category=business'
# submit_app 'name=Barclays&app_url=http://www.barclays.mobi/&category=business'
# submit_app 'name=Business Week&app_url=http://pda.businessweek.com/index.html&category=business'
# submit_app 'name=Capital One&app_url=http://m.capitalone.com/&category=business'
# submit_app 'name=Chase Mobile&app_url=http://chase.mobi/&category=business'
# submit_app 'name=Direct Textbook Mobile&app_url=http://www.directtextbook.com/mobile.php&category=business'
# submit_app 'name=E*TRADE&app_url=https://wireless.etrade.com/etrade/&category=business'
# submit_app 'name=Fidelity&app_url=http://wireless.fidelity.com/&category=business'
# submit_app 'name=Huntington Bank&app_url=http://mobile.huntington.com/&category=business'
# submit_app 'name=MarketWatch.com&app_url=http://www.marketwatch.com/m/&category=business'
# submit_app 'name=Orange County Credit Union&app_url=https://www.myoccu.mobi/&category=business'
# submit_app 'name=PayPal&app_url=https://mobile.paypal.com/&category=business'
# submit_app 'name=Scottrade&app_url=https://mtrading.scottrade.com/&category=business'
# submit_app 'name=Slate&app_url=http://mobile.slate.com/&category=business'
# submit_app 'name=StreetIQ Mobile&app_url=http://m.streetiq.com/&category=business'
# submit_app 'name=U.S. Bank&app_url=https://m.usbank.com/&category=business'
# submit_app 'name=USAA Mobile&app_url=http://mobile.usaa.com/&category=business'
# submit_app 'name=Wachovia&app_url=http://www.wachovia.com/mobile&category=business'
# submit_app 'name=Wells Fargo&app_url=https://mobile.wellsfargo.com/&category=business'

# submit_app 'name=Break.com&app_url=http://m.break.com/&category=entertainment'
# submit_app 'name=Buzzd&app_url=http://buzzd.com/m/&category=entertainment'
# submit_app 'name=Car and Driver&app_url=http://m.caranddriver.com/&category=entertainment'
# submit_app 'name=CMT&app_url=http://wap.cmt.com/&category=entertainment'
# submit_app 'name=Covergirl Mobile&app_url=http://m.covergirl.com/&category=entertainment'
# submit_app 'name=DirecTV&app_url=https://www.directv.com/m/&category=entertainment'
# submit_app 'name=Discovery Channel&app_url=http://discoverymobile.com/&category=entertainment'
# submit_app 'name=Fandango&app_url=http://mobile.fandango.com/&category=entertainment'
# submit_app 'name=Film-TV.com&app_url=http://www.film-tv.com/&category=entertainment'
# submit_app 'name=Flickr Mobile&app_url=http://m.flickr.com/&category=entertainment'
# submit_app 'name=Food Network&app_url=http://m.foodnetwork.com/&category=entertainment'
# submit_app 'name=Gameloft&app_url=http://gameloft.mobi/&category=entertainment'
# submit_app 'name=High School Musical 2&app_url=http://hsm2.mobi/&category=entertainment'
# submit_app 'name=IMDb&app_url=http://m.imdb.com/&category=entertainment'
# submit_app 'name=Maxim&app_url=http://mobile.maxim.com/&category=entertainment'
# submit_app "name=Men's Health&app_url=http://www.menshealth.com/mobile/&category=entertainment"
# submit_app 'name=MetroLyrics&app_url=http://m.metrolyrics.com/&category=entertainment'
# submit_app 'name=Mobile Stream Center&app_url=http://www.thestreamcenter.com/pda/&category=entertainment'
# submit_app 'name=Movie Habit&app_url=http://www.moviehabit.com/handheld/index.php&category=entertainment'
# submit_app 'name=Moviefone&app_url=http://wap.aol.com/moviefone/&category=entertainment'
# submit_app 'name=Movietickets.com&app_url=http://mobile.movietickets.com/&category=entertainment'
# submit_app 'name=Mr Movie Mobile&app_url=http://www.mrmovie.com/m/&category=entertainment'
# submit_app 'name=MTV&app_url=http://wap.mtv.com/&category=entertainment'
# submit_app 'name=NBC&app_url=http://m.nbc.com/&category=entertainment'
# submit_app 'name=Netflix Mobile&app_url=http://mobile.netflix.com/&category=entertainment'
# submit_app 'name=Photobucket&app_url=http://m.photobucket.com/&category=entertainment'
# submit_app 'name=Podcast.com Directory&app_url=http://mobile.podcast.com/&category=entertainment'
# submit_app 'name=popurls&app_url=http://popurls.mobi/&category=entertainment'
# submit_app 'name=Realtones&app_url=http://www.ctunes4.mobi/&category=entertainment'
# submit_app 'name=Restaurant Row!&app_url=http://www.restrow.com/avantgo/&category=entertainment'
# submit_app 'name=Serious Eats&app_url=http://mobile.seriouseats.com/&category=entertainment'
# submit_app 'name=SKY.fm Wireless Edition&app_url=http://www.sky.fm/mobile/&category=entertainment'
# submit_app 'name=Song Lyrics&app_url=http://lyrics.twilightwap.com/&category=entertainment'
# submit_app 'name=The Onion&app_url=http://mobile.theonion.com/&category=entertainment'
# submit_app 'name=ThrillNetwork&app_url=http://mobile.thrillnetwork.com/&category=entertainment'
# submit_app 'name=Thumb Games&app_url=http://thumbgames.mobi/&category=entertainment'
# submit_app 'name=TMZ&app_url=http://m.tmz.com/&category=entertainment'
# submit_app 'name=Top Gear (BBC)&app_url=http://www.bbc.co.uk/mobile/tv/topgear/&category=entertainment'
# submit_app 'name=TV Guide&app_url=http://wireless.tvguide.com/&category=entertainment'
# submit_app 'name=Variety.com&app_url=http://www.variety.com/index.asp?layout=channel&category=entertainment'
# submit_app 'name=vTap Video Search&app_url=http://m.vtap.com/&category=entertainment'
# submit_app 'name=YouTube&app_url=http://m.youtube.com/&category=entertainment'
# submit_app 'name=ZooVision&app_url=http://www.zoovision.com/mobile.html&category=entertainment'

# submit_app 'name=4Info&app_url=http://wap.4info.net/&category=info'
# submit_app 'name=AAA&app_url=http://mobile.aaa.com/&category=info'
# submit_app 'name=American Cancer Society&app_url=http://mobile.cancer.org/&category=info'
# submit_app 'name=Ask A Word&app_url=http://www.askaword.com/&category=info'
# submit_app 'name=AskMeNow&app_url=http://m.askmenow.com/&category=info'
# submit_app 'name=Block Layer&app_url=http://www.blocklayer.mobi/&category=info'
# submit_app 'name=CalcNexus&app_url=http://calcnexus.com/&category=info'
# submit_app 'name=Calculators&app_url=http://calcmp.com/&category=info'
# submit_app 'name=CalorieKing&app_url=http://mobile.calorieking.com/&category=info'
# submit_app 'name=Dictionary.com&app_url=http://m.reference.com/d/&category=info'
# submit_app 'name=Edmunds2Go!&app_url=http://pda.edmunds.com/&category=info'
# submit_app 'name=Fuel Economy&app_url=http://fueleconomy.gov/m/&category=info'
# submit_app 'name=Google Calendar&app_url=http://www.google.com/calendar/m&category=info'
# submit_app 'name=Google Docs&app_url=http://docs.google.com/m&category=info'
# submit_app 'name=Google Maps&app_url=http://google.com/gmm/&category=info'
# submit_app 'name=Google Translate&app_url=http://translate.google.com/m&category=info'
# submit_app 'name=Langtolang Translator&app_url=http://imode.langtolang.com/&category=info'
# submit_app 'name=Local.com&app_url=http://mobile.local.com/&category=info'
# submit_app 'name=LookWAYup&app_url=http://lookwayup.com/free/handheld.htm&category=info'
# submit_app 'name=Mobile Genealogy&app_url=http://www.daddezio.com/mobile.html&category=info'
# submit_app 'name=Mobile MapQuest&app_url=http://wap.mapquest.com/&category=info'
# submit_app 'name=PriceGrabber&app_url=http://www.atpgw.com/&category=info'
# submit_app 'name=PubMed for Handhelds (NLM)&app_url=http://pubmedhh.nlm.nih.gov/nlm/&category=info'
# submit_app 'name=Remember The Milk&app_url=http://m.rememberthemilk.com/&category=info'
# submit_app 'name=Seafood Watch&app_url=http://www.montereybayaquarium.org/mobile/sfw/&category=info'
# submit_app 'name=SitePoint&app_url=http://m.sitepoint.com/&category=info'
# submit_app 'name=SpaceRef Mobile&app_url=http://mspace.spaceref.com/&category=info'
# submit_app 'name=SpellBoy&app_url=http://m.spellboy.com/&category=info'
# submit_app 'name=SqueezeNet Handy Facts&app_url=http://www.squeezenet.com/HandyFact/default.htm&category=info'
# submit_app 'name=Sunnyvale Public Library&app_url=http://sunset.ci.sunnyvale.ca.us/airpac/jsp/airpacIndex.jsp&category=info'
# submit_app 'name=Traffic&app_url=http://mobi.traffic.com/traffic&category=info'
# submit_app 'name=USA.gov&app_url=http://mobile.usa.gov/&category=info'
# submit_app 'name=Wapedia (encyclopedia)&app_url=http://wapedia.mobi/en/&category=info'
# submit_app 'name=White Pages&app_url=http://m.whitepages.com/&category=info'
# submit_app 'name=Yelp Mobile&app_url=http://mobile.yelp.com/&category=info'
# submit_app 'name=Zondervan Bible Search&app_url=http://www.zbible.mobi/&category=info'

# submit_app 'name=ABC News&app_url=http://abcnews.mobi/&category=info'
# submit_app 'name=AP News&app_url=http://www.apnews.com/&category=info'
# submit_app 'name=AZCentral.com&app_url=http://www.azcentral.com/w2/&category=info'
# submit_app 'name=BBC&app_url=http://m.bbc.co.uk/news/&category=info'
# submit_app 'name=BBC | River&app_url=http://bbcriver.com/&category=info'
# submit_app 'name=Boston Globe&app_url=http://handheld.boston.com/avantgo/globe/&category=info'
# submit_app 'name=CBC News (Canada)&app_url=http://www.cbc.ca/mobile/&category=info'
# submit_app 'name=Central Florida News 13&app_url=http://www.cfnews13.com/mobile/&category=info'
# submit_app 'name=Chicago Tribune&app_url=http://mobile.chicagotribune.com/&category=info'
# submit_app 'name=Christian Science Monitor&app_url=http://www.csmonitor.com/textedition&category=info'
# submit_app 'name=Cincinnati.com&app_url=http://m.cincinnati.com/&category=info'
# submit_app 'name=CNBC&app_url=http://www.cnbc.com/&category=info'
# submit_app 'name=CNN Mobile&app_url=http://m.cnn.com/&category=info'
# submit_app 'name=CNN Political Ticker&app_url=http://politicalticker.blogs.cnn.com/&category=info'
# submit_app 'name=Dallas Morning News&app_url=http://www.dallasnews.com/mobile/index.html&category=info'
# submit_app 'name=Denver Post&app_url=http://m.denverpost.com/&category=info'
# submit_app 'name=Detroit Free Press&app_url=http://m.freep.com/&category=info'
# submit_app 'name=Detroit News&app_url=http://m.detnews.com/&category=info'
# submit_app 'name=El Paso Times&app_url=http://m.elpasotimes.com/&category=info'
# submit_app 'name=Examiner.com News&app_url=http://m.examiner.com/&category=info'
# submit_app 'name=Financial Times&app_url=http://m.ft.com/&category=info'
# submit_app 'name=Forbes&app_url=http://mobile.forbes.com/&category=info'
# submit_app 'name=FOX 4 Dallas/Fort Worth&app_url=http://wap.myfoxdfw.com/&category=info'
# submit_app 'name=FOX News&app_url=http://mobile.foxnews.com/&category=info'
# submit_app 'name=Google News&app_url=http://www.google.com/m/news&category=info'
# submit_app 'name=Hartford Courant&app_url=http://mobile.courant.com/&category=info'
# submit_app 'name=Houston Chronicle&app_url=http://mobile.chron.com/&category=info'
# submit_app 'name=International Herald Tribune&app_url=http://mobile.iht.com/&category=info'
# submit_app 'name=KKTV Colorado Springs&app_url=http://www.kktvtogo.com/&category=info'
# submit_app 'name=KOMO-TV Seattle&app_url=http://www.komotv.com/mobile&category=info'
# submit_app 'name=KSDK-TV St Louis&app_url=http://m.ksdk.com/&category=info'
# submit_app 'name=KSL Salt Lake City&app_url=http://www.myksl.com/&category=info'
# submit_app 'name=KTVU&app_url=http://wap.ktvu.com/&category=info'
# submit_app 'name=KUSA-TV Denver&app_url=http://m.9news.com/&category=info'
# submit_app 'name=Local TV News&app_url=http://www.localwireless.com/wap/&category=info'
# submit_app 'name=Los Angeles Times&app_url=http://mobile.latimes.com/wap/pda/stations/3/&category=info'
# submit_app 'name=NBC 5 West Palm Beach&app_url=http://www.nc5now.com/&category=info'
# submit_app 'name=New York Post&app_url=http://m.nypost.com/&category=info'
# submit_app 'name=news4mobile&app_url=http://www.news4mobile.com/&category=info'
# submit_app 'name=Newsphone.com&app_url=http://www.newsphone.com/&category=info'
# submit_app 'name=NJ.com&app_url=http://www.nj.com/mobile/&category=info'
# submit_app 'name=NPR&app_url=http://m.npr.org/&category=info'
# submit_app 'name=NPR.org&app_url=http://thin.npr.org/&category=info'
# submit_app 'name=NY Times&app_url=http://mobile.nytimes.com/&category=info'
# submit_app 'name=NY Times | River&app_url=http://nytimesriver.com/&category=info'
# submit_app 'name=Pittsburgh Post-Gazette&app_url=http://www.post-gazette.com/&category=info'
# submit_app 'name=Politico&app_url=http://mobile.politico.com/&category=info'
# submit_app 'name=Reuters News&app_url=http://mobile.reuters.com/&category=info'
# submit_app 'name=Rocky Mountain News&app_url=http://m.rockymountainnews.com/&category=info'
# submit_app 'name=Salon.com Mobile&app_url=http://mobile.salon.com/&category=info'
# submit_app 'name=San Jose Mercury News&app_url=http://m.mercurynews.com/&category=info'
# submit_app 'name=Seattle P-I&app_url=http://seattlepi.nwsource.com/pqa/&category=info'
# submit_app 'name=Seattle Times&app_url=http://seattletimes.com/wap&category=info'
# submit_app 'name=Sign On San Diego&app_url=http://signon.mobi/&category=info'
# submit_app 'name=Star-Tribune&app_url=http://www.startribune.com/news/palm/avantgo/&category=info'
# submit_app 'name=Sun-Sentinel Mobile&app_url=http://mobile.sun-sentinel.com/&category=info'
# submit_app 'name=Tampa Bay Online&app_url=http://m.tbo.com/&category=info'
# submit_app 'name=The Guardian&app_url=http://m.guardian.co.uk/&category=info'
# submit_app 'name=The Hill&app_url=http://mobile.thehill.com/&category=info'
# submit_app 'name=The Huffington Post&app_url=http://m.huffingtonpost.com/&category=info'
# submit_app 'name=The Olympian&app_url=http://m.theolympian.com/&category=info'
# submit_app 'name=The Register Mobile&app_url=http://mobile.theregister.com/trm/pda&category=info'
# submit_app 'name=The Sacramento Bee&app_url=http://www.sacbee.mobi/&category=info'
# submit_app 'name=The Sun (UK)&app_url=http://www.thesun.mobi/&category=info'
# submit_app 'name=TIME&app_url=http://mobile.time.com/&category=info'
# submit_app 'name=Topix&app_url=http://www.topix.com/&category=info'
# submit_app 'name=USA Today&app_url=http://wap.usatoday.com/&category=info'
# submit_app 'name=Wall Street Journal&app_url=http://mobile2.wsj.com/&category=info'
# submit_app 'name=Washington Post&app_url=http://mobile.washingtonpost.com/&category=info'
# submit_app 'name=WGRZ-TV Buffalo&app_url=http://m.wgrz.com/&category=info'
# submit_app 'name=WPVI-TV Philadelphia&app_url=http://www.6abctogo.com/&category=info'
# submit_app 'name=Yahoo! News&app_url=http://m.yahoo.com/p/news&category=info'

# submit_app 'name=4Info&app_url=http://wap.4info.net/&category=portal'
# submit_app 'name=AOL Mobile Search&app_url=http://wap.aol.com/portal/searchindex.do&category=portal'
# submit_app 'name=AOL Portal&app_url=http://wap.aol.com/portal/&category=portal'
# submit_app 'name=Comcast Mobile&app_url=http://m.comcast.net/&category=portal'
# submit_app 'name=eBuddy Mobile&app_url=http://www.ebuddy.com/mobile/&category=portal'
# submit_app 'name=Facebook&app_url=http://m.facebook.com/&category=portal'
# submit_app 'name=five-alive portal&app_url=http://pda.five-alive.com/&category=portal'
# submit_app 'name=getFROG.com&app_url=http://getfrog.com/&category=portal'
# submit_app 'name=Google Personalized&app_url=http://www.google.com/ig/mobile?output=pda&category=portal'
# submit_app 'name=Google Reader&app_url=http://www.google.com/reader/m/view/&category=portal'
# submit_app 'name=GrandCentral&app_url=http://grandcentral.com/mobile&category=portal'
# submit_app 'name=portalSpace&app_url=http://www.infospace.com/info.avant/&category=portal'
# submit_app 'name=meongo.com&app_url=http://m.meongo.com/&category=portal'
# submit_app 'name=Microsoft&app_url=http://mobile.microsoft.com/&category=portal'
# submit_app 'name=MSN Mobile&app_url=http://mobile.msn.com/pocketpc/&category=portal'
# submit_app 'name=MSN UK&app_url=http://mobile.uk.msn.com/device/default.aspx&category=portal'
# submit_app 'name=My PDA Site&app_url=http://mypdasite.com/&category=portal'
# submit_app 'name=MySpace&app_url=http://mobile.myspace.com/&category=portal'
# submit_app 'name=Netvibes&app_url=http://m.netvibes.com/&category=portal'
# submit_app 'name=PDA Homepage&app_url=http://www.pdahomepage.com/&category=portal'
# submit_app 'name=PDAportal.com&app_url=http://pdaportal.com/&category=portal'
# submit_app 'name=Pocket PC Magazine&app_url=http://www.pocketpcmag.com/mobile/mobile.asp&category=portal'
# submit_app 'name=SqueezeNet&app_url=http://squeezenet.com/&category=portal'
# submit_app 'name=The Casual Traveler&app_url=http://www.thecasualtraveler.com/mini.htm&category=portal'
# submit_app 'name=Towza&app_url=http://m.towza.com/&category=portal'
# submit_app 'name=Twitter&app_url=http://m.twitter.com/&category=portal'
# submit_app 'name=wapSwap&app_url=http://www.wapswap.com/index.php&category=portal'
# submit_app 'name=Windows Live&app_url=http://mobile.live.com/wml/&category=portal'
# submit_app 'name=Yahoo!&app_url=http://us.m.yahoo.com/&category=portal'
# submit_app 'name=Yahoo! Mail&app_url=http://us.m.yahoo.com/p/mail&category=portal'
# submit_app 'name=YesWAP Mobile&app_url=http://yeswap.com/&category=portal'

# submit_app 'name=Ask&app_url=http://m.ask.com/&category=search'
# submit_app 'name=Bing&app_url=http://m.bing.com/&category=search'
# submit_app 'name=Clusty Mobile Search&app_url=http://m.clusty.com/&category=search'
# submit_app 'name=Google&app_url=http://www.google.com/xhtml&category=search'
# submit_app 'name=Mowser&app_url=http://mowser.com/&category=search'
# submit_app 'name=Technorati&app_url=http://mobile.technorati.com/&category=search'
# submit_app 'name=Yahoo&app_url=http://us.m.yahoo.com/p/search&category=search'
# submit_app 'name=Yippy&app_url=http://m.yippy.com/&category=search'

# submit_app 'name=Amazon&app_url=http://amazon.com/gp/aw/h.html&category=shopping'
# submit_app 'name=Barcle&app_url=http://mobile.barcle.com/&category=shopping'
# submit_app 'name=Barnes %26 Noble.com - Mobile&app_url=http://www.barnesandnoble.com/mobile/&category=shopping'
# submit_app 'name=BestBookBuys&app_url=http://www.bestwebbuys.com/books/mcompare&category=shopping'
# submit_app 'name=BestBuy&app_url=http://m.bestbuy.com/&category=shopping'
# submit_app 'name=BMW&app_url=http://bmw.mobi/&category=shopping'
# submit_app 'name=eBay mobile&app_url=http://wap.ebay.com/&category=shopping'
# submit_app 'name=Fat Wallet&app_url=http://www.fatwallet.mobi/forums/&category=shopping'
# submit_app 'name=FedEx&app_url=https://m.fedex.com/&category=shopping'
# submit_app 'name=Newegg.com&app_url=http://m.newegg.com/&category=shopping'
# submit_app 'name=Nordstrom&app_url=http://nordstrom.mobi/&category=shopping'
# submit_app 'name=PayPal&app_url=https://mobile.paypal.com/&category=shopping'
# submit_app 'name=Pocket Deal&app_url=http://www.pocketdeal.com/mobile/index.aspx&category=shopping'
# submit_app 'name=SlickDeals.net&app_url=http://m.slickdeals.net/&category=shopping'
# submit_app 'name=SplashData&app_url=http://www.splashdata.com/mobile/&category=shopping'
# submit_app 'name=Target&app_url=http://sites.target.com/site/en/spot/mobile.jsp&category=shopping'
# submit_app 'name=UPS&app_url=http://mobile.ups.com/ups/&category=shopping'
# submit_app 'name=Zillow&app_url=http://mobile.zillow.com/&category=shopping'

# submit_app 'name=BBC Sport Mobile - London 2012 Olympics&app_url=http://www.bbc.co.uk/sport/mobile/olympics/2012&category=sports'
# submit_app 'name=Boston Globe Sports&app_url=http://handheld.boston.com/avantgo/sports/&category=sports'
# submit_app 'name=CBS Sports&app_url=http://wap.cbssports.com/&category=sports'
# submit_app 'name=CSN Bay Area&app_url=http://www.csnbayarea.com/mobile&category=sports'
# submit_app 'name=ESPN&app_url=http://espn.mobi/&category=sports'
# submit_app 'name=ESPN (lite)&app_url=http://espn.go.com/wireless/palm/index.htm&category=sports'
# submit_app 'name=Eurosport Formula 1&app_url=http://m.yahoo.com/w/yformula1&category=sports'
# submit_app 'name=Eurosport Mobile&app_url=http://m.eurosport.com/&category=sports'
# submit_app 'name=FOX Sports&app_url=http://extreme.mobile.msn.com/sports/&category=sports'
# submit_app 'name=Goal.com - Soccer&app_url=http://m.goal.com/&category=sports'
# submit_app 'name=London 2012 Olympics - Official&app_url=http://m.london2012.com/&category=sports'
# submit_app 'name=Minor League Baseball&app_url=http://milb.com/&category=sports'
# submit_app 'name=MLB.com&app_url=http://wap.mlb.com/&category=sports'
# submit_app 'name=Mobile Fantasy Sports Portal&app_url=http://m.fantasysp.com/&category=sports'
# submit_app 'name=Motorcycle Events&app_url=http://mobile.weaselsspfld.com/&category=sports'
# submit_app 'name=NASCAR&app_url=http://m.nascar.com/&category=sports'
# submit_app 'name=NBC Olympics Home&app_url=http://m.nbcolympics.com/&category=sports'
# submit_app 'name=NBC Sports&app_url=http://mobile.nbcsports.com/&category=sports'
# submit_app 'name=NFL.com&app_url=http://wap.nfl.com/&category=sports'
# submit_app 'name=NHL&app_url=http://m.nhl.com/&category=sports'
# submit_app 'name=Olympics Home - ESPN&app_url=http://m.espn.go.com/extra/olympics/&category=sports'
# submit_app 'name=PGA Tour&app_url=http://mobile.pgatour.com/&category=sports'
# submit_app 'name=SB Nation&app_url=http://mobile.sbnation.com/&category=sports'
# submit_app 'name=SBNation - 2012 Olympics&app_url=http://mobile.sbnation.com/london-olympics-2012&category=sports'
# submit_app 'name=ScoresAndOdds.com&app_url=http://scoresandodds.com/pda/&category=sports'
# submit_app 'name=SI.com&app_url=http://m.si.com/&category=sports'
# submit_app 'name=Soccerway&app_url=http://www.soccerway.mobi/&category=sports'
# submit_app 'name=sports<>tap&app_url=http://sportstap.mobi/&category=sports'
# submit_app 'name=The Sporting News&app_url=http://m.sportingnews.com/&category=sports'
# submit_app 'name=TSN Canada Sports&app_url=http://tsn.ca/&category=sports'
# submit_app 'name=Yahoo! Sports&app_url=http://us.m.yahoo.com/p/sports&category=sports'

# submit_app 'name=Brighthand&app_url=http://www.brighthand.com/mobile/&category=technology'
# submit_app 'name=CNET&app_url=http://m.cnet.com/&category=technology'
# submit_app 'name=CNET News.com&app_url=http://m.news.com/&category=technology'
# submit_app 'name=CrackBerry.com&app_url=http://wap.crackberry.com/&category=technology'
# submit_app 'name=Engadget&app_url=http://m.engadget.com/&category=technology'
# submit_app 'name=Forum Nokia Mobile&app_url=http://forumnokia.mobi/&category=technology'
# submit_app 'name=GSMArena.com&app_url=http://m.gsmarena.com/&category=technology'
# submit_app 'name=Joystiq&app_url=http://m.joystiq.com/&category=technology'
# submit_app 'name=Mobile speed test&app_url=http://www.dslreports.com/mspeed&category=technology'
# submit_app 'name=PalmInfocenter&app_url=http://www.palminfocenter.com/mobile/&category=technology'
# submit_app 'name=Slashdot&app_url=http://slashdot.org/palm/&category=technology'
# submit_app 'name=Techmeme&app_url=http://techmeme.com/m/&category=technology'
# submit_app 'name=Treocentral&app_url=http://treo.tc/&category=technology'
# submit_app 'name=Ubergizmo&app_url=http://ubergizmo.mobi/&category=technology'
# submit_app 'name=Wired News&app_url=http://www.wired.com/news_drop/palmpilot/&category=technology'

# submit_app 'name=Air Canada&app_url=http://mobile.aircanada.com/home&category=travel'
# submit_app 'name=Air-France&app_url=http://mobile.airfrance.com/&category=travel'
# submit_app 'name=American Airlines&app_url=http://mobile.aa.com/&category=travel'
# submit_app 'name=Amtrak&app_url=http://m.amtrak.com'
# submit_app 'name=BART&app_url=http://m.bart.gov/&category=travel'
# submit_app 'name=California Road Conditions&app_url=http://www.dot.ca.gov/cgi-bin/roadscell.cgi&category=travel'
# submit_app 'name=Caltrain Schedules&app_url=http://m.icaltrain.com/&category=travel'
# submit_app 'name=City.mobi&app_url=http://city.mobi/&category=travel'
# submit_app 'name=Citysearch&app_url=http://m.citysearch.com/&category=travel'
# submit_app 'name=Continental Airlines&app_url=http://pda.continental.com/&category=travel'
# submit_app 'name=Delta Airlines&app_url=http://mobile.delta.com/&category=travel'
# submit_app 'name=Flight Stats&app_url=http://mobile.flightstats.com/go/Mobile/&category=travel'
# submit_app 'name=HopStop&app_url=http://hopstop.com/pda&category=travel'
# submit_app 'name=HopStop bus/subway&app_url=http://www.hopstop.com/pda&category=travel'
# submit_app 'name=Jet Blue&app_url=http://mobile.jetblue.com/&category=travel'
# submit_app 'name=kayak mobile&app_url=http://www.kayak.com/moby/&category=travel'
# submit_app 'name=KLM&app_url=http://www.klm.com/travel/mobile_en/mobile.htm&category=travel'
# submit_app 'name=lastminute.com&app_url=http://mobile.lastminute.com/&category=travel'
# submit_app 'name=Lonely Planet&app_url=http://m.lonelyplanet.com/&category=travel'
# submit_app 'name=Northwest Airlines&app_url=http://wireless.nwa.com/&category=travel'
# submit_app 'name=OpenTable&app_url=http://m.opentable.com/&category=travel'
# submit_app 'name=Orbitz&app_url=http://mobile.orbitz.com/&category=travel'
# submit_app 'name=Pilot Maps and Directions&app_url=http://pilot.mobi/&category=travel'
# submit_app 'name=Sabre Virtually There&app_url=http://virtuallythere.com/&category=travel'
# submit_app 'name=SeatGuru.com&app_url=http://mobile.seatguru.com/&category=travel'
# submit_app 'name=Ski Travel Nevada&app_url=http://skitravelnevada.mobi/&category=travel'
# submit_app 'name=Southwest Airlines&app_url=http://mobile.southwest.com/&category=travel'
# submit_app 'name=Starbucks&app_url=http://mobile.starbucks.com/&category=travel'
# submit_app 'name=TripAdvisor&app_url=http://www.tripadvisor.com/&category=travel'
# submit_app 'name=TripIt&app_url=http://m.tripit.com/&category=travel'
# submit_app 'name=United Airlines&app_url=http://mobile.united.com/&category=travel'
# submit_app 'name=Urbanspoon: Choose a city&app_url=http://www.urbanspoon.com/m&category=travel'
# submit_app 'name=US Airways&app_url=http://www.usairways.com/&category=travel'
# submit_app 'name=WestJet Mobile&app_url=http://mobile.westjet.com/&category=travel'
# submit_app 'name=wherethere&app_url=http://wherethere.mobi/&category=travel'
# submit_app 'name=Whistler Travel Guide&app_url=http://whistler.mobi/&category=travel'
# submit_app 'name=Zagat&app_url=http://zagat.mobi/&category=travel'

# submit_app 'name=AccuWeather&app_url=http://wap.accuweather.com/&category=weather'
# submit_app 'name=ForeCA Weather&app_url=http://foreca.mobi/&category=weather'
# submit_app 'name=National Weather Service&app_url=http://mobile.srh.weather.gov/&category=weather'
# submit_app 'name=PDA Animated Weather&app_url=http://www.ssec.wisc.edu/data/paw/&category=weather'
# submit_app 'name=The Weather Channel&app_url=http://xhtml.weather.com/xhtml/&category=weather'
# submit_app 'name=Weather Underground&app_url=http://m.wund.com/&category=weather'
